import type { Task, Team, Label, Project, Section } from 'src/module/timebox/types';

// Mock Labels
export const MOCK_LABELS: Label[] = [
  { id: '1', name: 'Bug', color: '#FA383E', position: 1, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: '2', name: 'Feature', color: '#22C55E', position: 2, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: '3', name: 'Urgent', color: '#FFAB00', position: 3, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: '4', name: 'Documentation', color: '#00B8D9', position: 4, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
  { id: '5', name: 'Review', color: '#9C27B0', position: 5, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
];

// Mock Sections
export const MOCK_SECTIONS: Section[] = [
  { id: 'sec-1', projectId: 'proj-1', name: 'Backend', position: 1, createdAt: '2026-01-01', updatedAt: '2026-01-01', collapsed: false },
  { id: 'sec-2', projectId: 'proj-1', name: 'Frontend', position: 2, createdAt: '2026-01-01', updatedAt: '2026-01-01', collapsed: false },
  { id: 'sec-3', projectId: 'proj-1', name: 'DevOps', position: 3, createdAt: '2026-01-01', updatedAt: '2026-01-01', collapsed: false },
  { id: 'sec-4', projectId: 'proj-1', name: 'Testing', position: 4, createdAt: '2026-01-01', updatedAt: '2026-01-01', collapsed: false },
];

// Mock Tasks
export const MOCK_TASKS: Task[] = [
  {
    id: 'task-inbox-1',
    projectId: 'inbox',
    title: 'Review pull requests',
    description: 'Review and approve pending pull requests from the team',
    priority: 'high',
    sectionId: null,
    dueDate: '2026-05-12',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[0], MOCK_LABELS[4]],
    assigneeIds: [],
    position: 1,
  },
  {
    id: 'task-inbox-2',
    projectId: 'inbox',
    title: 'Update meeting notes',
    description: 'Compile and distribute notes from the weekly standup meeting',
    priority: 'medium',
    sectionId: null,
    dueDate: '2026-05-14',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[3]],
    assigneeIds: [],
    position: 2,
  },
  {
    id: 'task-inbox-3',
    projectId: 'inbox',
    title: 'Design new dashboard layout',
    description: 'Create wireframes and mockups for the redesigned analytics dashboard',
    priority: 'high',
    sectionId: null,
    dueDate: '2026-05-16',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[1], MOCK_LABELS[2]],
    assigneeIds: [],
    position: 3,
  },
  {
    id: 'task-inbox-4',
    projectId: 'inbox',
    title: 'Set up staging environment',
    description: 'Configure staging server with latest changes for QA testing',
    priority: 'urgent',
    sectionId: null,
    dueDate: '2026-05-13',
    createdAt: '2026-05-12',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[0]],
    assigneeIds: [],
    position: 4,
  },
  {
    id: 'task-inbox-5',
    projectId: 'inbox',
    title: 'Write API documentation',
    description: 'Document REST endpoints for the new authentication service',
    priority: 'medium',
    sectionId: null,
    dueDate: '2026-05-18',
    createdAt: '2026-05-12',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[3]],
    assigneeIds: [],
    position: 5,
  },
  {
    id: 'task-inbox-6',
    projectId: 'inbox',
    title: 'Refactor user profile component',
    description: 'Improve performance of the user profile rendering',
    priority: 'low',
    sectionId: null,
    dueDate: '2026-05-20',
    createdAt: '2026-05-12',
    updatedAt: '2026-05-12',
    labels: [],
    assigneeIds: [],
    position: 6,
  },
  {
    id: 'task-inbox-7',
    projectId: 'inbox',
    title: 'Update dependency versions',
    description: 'Bump minor versions and verify compatibility',
    priority: 'low',
    sectionId: null,
    dueDate: '2026-05-22',
    createdAt: '2026-05-12',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[4]],
    assigneeIds: [],
    position: 7,
  },
  {
    id: 'task-inbox-8',
    projectId: 'inbox',
    title: 'Investigate crash on Android',
    description: 'Debug and fix the crash reported on Android 14 devices',
    priority: 'urgent',
    sectionId: null,
    dueDate: '2026-05-11',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-12',
    completedAt: '2026-05-11T15:30:00Z',
    labels: [MOCK_LABELS[0]],
    assigneeIds: [],
    position: 8,
  },
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Implement authentication module',
    description: 'Create login/signup functionality with JWT tokens',
    priority: 'high',
    sectionId: 'sec-1',
    dueDate: '2026-05-20',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[1], MOCK_LABELS[2]],
    assigneeIds: [],
    position: 1,
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Fix login page UI issues',
    description: 'Resolve responsive design problems on mobile devices',
    priority: 'medium',
    sectionId: 'sec-2',
    dueDate: '2026-05-18',
    createdAt: '2026-05-05',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[0], MOCK_LABELS[3]],
    assigneeIds: [],
    position: 2,
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Setup database migrations',
    description: 'Configure Flyway for automated schema versioning',
    priority: 'urgent',
    sectionId: 'sec-1',
    dueDate: '2026-05-15',
    createdAt: '2026-05-08',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[1]],
    assigneeIds: [],
    position: 3,
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with examples',
    priority: 'medium',
    sectionId: 'sec-4',
    dueDate: '2026-05-25',
    createdAt: '2026-05-02',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[3]],
    assigneeIds: [],
    position: 4,
    completedAt: null,
  },
  {
    id: 'task-5',
    projectId: 'proj-2',
    title: 'Optimize bundle size',
    description: 'Reduce main bundle from 500KB to 300KB',
    priority: 'high',
    sectionId: 'sec-2',
    dueDate: '2026-05-10',
    createdAt: '2026-04-25',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[1]],
    assigneeIds: [],
    position: 1,
    completedAt: '2026-05-10T10:30:00Z',
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    priority: 'high',
    sectionId: 'sec-3',
    dueDate: '2026-05-22',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[1]],
    assigneeIds: [],
    position: 2,
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    title: 'Update dependencies',
    description: 'Upgrade React, TypeScript, and other major packages',
    priority: 'low',
    sectionId: null,
    dueDate: '2026-06-01',
    createdAt: '2026-05-05',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[3]],
    assigneeIds: [],
    position: 3,
  },
  {
    id: 'task-8',
    projectId: 'proj-1',
    title: 'Code review for PR #123',
    description: 'Review authentication changes from team member',
    priority: 'medium',
    sectionId: 'sec-4',
    dueDate: '2026-05-13',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-12',
    labels: [MOCK_LABELS[4]],
    assigneeIds: [],
    position: 5,
  },
];

// Mock Projects
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'inbox',
    name: 'Inbox',
    description: 'Default inbox project',
    color: '#6366F1',
    isFavorite: true,
    isArchived: false,
    isInbox: true,
    viewMode: 'board',
    position: 0,
    sections: [],
    tasks: [
      {
        id: 'task-inbox-1',
        projectId: 'inbox',
        title: 'Review pull requests',
        description: 'Review and approve pending pull requests from the team',
        priority: 'high',
        sectionId: null,
        dueDate: '2026-05-12',
        createdAt: '2026-05-10',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[0], MOCK_LABELS[4]],
        assigneeIds: [],
        position: 1,
      },
      {
        id: 'task-inbox-2',
        projectId: 'inbox',
        title: 'Update meeting notes',
        description: 'Compile and distribute notes from the weekly standup meeting',
        priority: 'medium',
        sectionId: null,
        dueDate: '2026-05-14',
        createdAt: '2026-05-11',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[3]],
        assigneeIds: [],
        position: 2,
      },
      {
        id: 'task-inbox-3',
        projectId: 'inbox',
        title: 'Design new dashboard layout',
        description: 'Create wireframes and mockups for the redesigned analytics dashboard',
        priority: 'high',
        sectionId: null,
        dueDate: '2026-05-16',
        createdAt: '2026-05-11',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[1], MOCK_LABELS[2]],
        assigneeIds: [],
        position: 3,
      },
      {
        id: 'task-inbox-4',
        projectId: 'inbox',
        title: 'Set up staging environment',
        description: 'Configure staging server with latest changes for QA testing',
        priority: 'urgent',
        sectionId: null,
        dueDate: '2026-05-13',
        createdAt: '2026-05-12',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[0]],
        assigneeIds: [],
        position: 4,
      },
      {
        id: 'task-inbox-5',
        projectId: 'inbox',
        title: 'Write API documentation',
        description: 'Document REST endpoints for the new authentication service',
        priority: 'medium',
        sectionId: null,
        dueDate: '2026-05-18',
        createdAt: '2026-05-12',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[3]],
        assigneeIds: [],
        position: 5,
      },
      {
        id: 'task-inbox-6',
        projectId: 'inbox',
        title: 'Refactor user profile component',
        description: 'Improve performance of the user profile rendering',
        priority: 'low',
        sectionId: null,
        dueDate: '2026-05-20',
        createdAt: '2026-05-12',
        updatedAt: '2026-05-12',
        labels: [],
        assigneeIds: [],
        position: 6,
      },
      {
        id: 'task-inbox-7',
        projectId: 'inbox',
        title: 'Update dependency versions',
        description: 'Bump minor versions and verify compatibility',
        priority: 'low',
        sectionId: null,
        dueDate: '2026-05-22',
        createdAt: '2026-05-12',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[4]],
        assigneeIds: [],
        position: 7,
      },
      {
        id: 'task-inbox-8',
        projectId: 'inbox',
        title: 'Investigate crash on Android',
        description: 'Debug and fix the crash reported on Android 14 devices',
        priority: 'urgent',
        sectionId: null,
        dueDate: '2026-05-11',
        createdAt: '2026-05-10',
        updatedAt: '2026-05-12',
        completedAt: '2026-05-11T15:30:00Z',
        labels: [MOCK_LABELS[0]],
        assigneeIds: [],
        position: 8,
      },
    ],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
    teamId: null,
    _count: { tasks: 7, completedTasks: 1 },
  },
  {
    id: 'proj-1',
    name: 'Timebox API',
    description: 'Backend API for task management system',
    color: '#1976D2',
    isFavorite: true,
    isArchived: false,
    isInbox: false,
    viewMode: 'board',
    position: 1,
    sections: MOCK_SECTIONS.slice(0, 2),
    tasks: [
      {
        id: 'task-1',
        projectId: 'proj-1',
        title: 'Implement authentication module',
        description: 'Create login/signup functionality with JWT tokens',
        priority: 'high',
        sectionId: 'sec-1',
        dueDate: '2026-05-20',
        createdAt: '2026-05-01',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[1], MOCK_LABELS[2]],
        assigneeIds: [],
        position: 1,
      },
      {
        id: 'task-2',
        projectId: 'proj-1',
        title: 'Fix login page UI issues',
        description: 'Resolve responsive design problems on mobile devices',
        priority: 'medium',
        sectionId: 'sec-2',
        dueDate: '2026-05-18',
        createdAt: '2026-05-05',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[0], MOCK_LABELS[3]],
        assigneeIds: [],
        position: 2,
      },
      {
        id: 'task-3',
        projectId: 'proj-1',
        title: 'Setup database migrations',
        description: 'Configure Flyway for automated schema versioning',
        priority: 'urgent',
        sectionId: 'sec-1',
        dueDate: '2026-05-15',
        createdAt: '2026-05-08',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[1]],
        assigneeIds: [],
        position: 3,
      },
      {
        id: 'task-4',
        projectId: 'proj-1',
        title: 'Write API documentation',
        description: 'Document all REST endpoints with examples',
        priority: 'medium',
        sectionId: 'sec-4',
        dueDate: '2026-05-25',
        createdAt: '2026-05-02',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[3]],
        assigneeIds: [],
        position: 4,
        completedAt: null,
      },
      {
        id: 'task-8',
        projectId: 'proj-1',
        title: 'Code review for PR #123',
        description: 'Review authentication changes from team member',
        priority: 'medium',
        sectionId: 'sec-4',
        dueDate: '2026-05-13',
        createdAt: '2026-05-11',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[4]],
        assigneeIds: [],
        position: 5,
      },
    ],
    createdAt: '2026-04-01',
    updatedAt: '2026-05-12',
    teamId: 'team-1',
    _count: { tasks: 5, completedTasks: 1 },
  },
  {
    id: 'proj-2',
    name: 'Timebox Web',
    description: 'Frontend React application',
    color: '#388E3C',
    isFavorite: true,
    isArchived: false,
    isInbox: false,
    viewMode: 'board',
    position: 2,
    sections: MOCK_SECTIONS.slice(1, 3),
    tasks: [
      {
        id: 'task-5',
        projectId: 'proj-2',
        title: 'Optimize bundle size',
        description: 'Reduce main bundle from 500KB to 300KB',
        priority: 'high',
        sectionId: 'sec-2',
        dueDate: '2026-05-10',
        createdAt: '2026-04-25',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[1]],
        assigneeIds: [],
        position: 1,
        completedAt: '2026-05-10T10:30:00Z',
      },
      {
        id: 'task-6',
        projectId: 'proj-2',
        title: 'Setup CI/CD pipeline',
        description: 'Configure GitHub Actions for automated testing and deployment',
        priority: 'high',
        sectionId: 'sec-3',
        dueDate: '2026-05-22',
        createdAt: '2026-05-01',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[1]],
        assigneeIds: [],
        position: 2,
      },
      {
        id: 'task-7',
        projectId: 'proj-2',
        title: 'Update dependencies',
        description: 'Upgrade React, TypeScript, and other major packages',
        priority: 'low',
        sectionId: null,
        dueDate: '2026-06-01',
        createdAt: '2026-05-05',
        updatedAt: '2026-05-12',
        labels: [MOCK_LABELS[3]],
        assigneeIds: [],
        position: 3,
      },
    ],
    createdAt: '2026-04-01',
    updatedAt: '2026-05-12',
    teamId: 'team-1',
    _count: { tasks: 3, completedTasks: 1 },
  },
  {
    id: 'proj-3',
    name: 'Mobile App',
    description: 'React Native mobile application',
    color: '#D32F2F',
    isFavorite: false,
    isArchived: false,
    isInbox: false,
    viewMode: 'board',
    position: 3,
    sections: MOCK_SECTIONS,
    tasks: [],
    createdAt: '2026-04-15',
    updatedAt: '2026-05-12',
    teamId: 'team-2',
    _count: { tasks: 0, completedTasks: 0 },
  },
  {
    id: 'proj-4',
    name: 'Infrastructure',
    description: 'DevOps and infrastructure setup',
    color: '#F57C00',
    isFavorite: false,
    isArchived: false,
    isInbox: false,
    viewMode: 'board',
    position: 4,
    sections: [MOCK_SECTIONS[2]],
    tasks: [],
    createdAt: '2026-05-01',
    updatedAt: '2026-05-12',
    teamId: 'team-1',
    _count: { tasks: 0, completedTasks: 0 },
  },
];

// Mock Teams
export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Core Team',
    description: 'Main development team',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
    position: 1,
    members: [
      { userId: 'user-1', userName: 'Alice Johnson', userEmail: 'alice@example.com', role: 'owner', joinedAt: '2026-01-01' },
      { userId: 'user-2', userName: 'Bob Smith', userEmail: 'bob@example.com', role: 'member', joinedAt: '2026-01-01' },
      { userId: 'user-3', userName: 'Carol White', userEmail: 'carol@example.com', role: 'member', joinedAt: '2026-01-01' },
    ],
    _count: { members: 3, projects: 0 },
  },
  {
    id: 'team-2',
    name: 'Mobile Team',
    description: 'Mobile development team',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
    position: 2,
    members: [
      { userId: 'user-4', userName: 'David Brown', userEmail: 'david@example.com', role: 'owner', joinedAt: '2026-01-01' },
      { userId: 'user-5', userName: 'Eva Davis', userEmail: 'eva@example.com', role: 'member', joinedAt: '2026-01-01' },
    ],
    _count: { members: 2, projects: 0 },
  },
];

// Mock data getter functions
export function getMockTasks(projectId?: string, priority?: string): Task[] {
  let filtered = [...MOCK_TASKS];

  if (projectId) {
    filtered = filtered.filter((t) => t.projectId === projectId);
  }

  if (priority) {
    filtered = filtered.filter((t) => t.priority === priority);
  }

  return filtered;
}

export function getMockProjects(teamId?: string, archived = false): Project[] {
  let filtered = [...MOCK_PROJECTS];

  if (teamId) {
    filtered = filtered.filter((p) => p.teamId === teamId);
  }

  filtered = filtered.filter((p) => p.isArchived === archived);

  return filtered;
}

export function getMockTaskById(taskId: string): Task | undefined {
  return MOCK_TASKS.find((t) => t.id === taskId);
}

export function getMockProjectById(projectId: string): Project | undefined {
  return MOCK_PROJECTS.find((p) => p.id === projectId);
}

export function getMockTeamById(teamId: string): Team | undefined {
  return MOCK_TEAMS.find((t) => t.id === teamId);
}

export function getMockTasksByDueDate(startDate: string, endDate: string): Task[] {
  return MOCK_TASKS.filter((t) => {
    if (!t.dueDate) return false;
    return t.dueDate >= startDate && t.dueDate <= endDate;
  });
}

export function getMockTasksForToday(): Task[] {
  const today = new Date().toISOString().split('T')[0];
  return MOCK_TASKS.filter((t) => {
    if (!t.dueDate) return false;
    return t.dueDate === today && !t.completedAt;
  });
}
